//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportPRJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stud
    {
        public int id { get; set; }
        public string NameS { get; set; }
        public string NameKh { get; set; }
        public string NameP { get; set; }
        public string Tavalod { get; set; }
        public string CodeM { get; set; }
        public string Tel { get; set; }
        public string Payeh { get; set; }
        public int Moadel { get; set; }
        public string Tarikh { get; set; }
        public byte[] Pic { get; set; }
    }
}
